# Use version 3.8 of the Docker Compose file format.
# This version is widely compatible and supports most features.
version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      #      MARIADB_DATABASE: my_database
      MARIADB_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
volumes:
  db_data:
